Traceback (most recent call last):
  File "/home/lhaag/BA/MultiColumnCorrupion/src/data_imputation_paper/experiment.py", line 135, in run
    evaluator.evaluate(self._num_repetitions)
  File "/home/lhaag/BA/MultiColumnCorrupion/src/data_imputation_paper/evaluation_corrupted.py", line 334, in evaluate
    result_temp.append(
  File "/home/lhaag/BA/MultiColumnCorrupion/src/data_imputation_paper/evaluation_corrupted.py", line 64, in append
    self._update_results(
  File "/home/lhaag/BA/MultiColumnCorrupion/src/data_imputation_paper/evaluation_corrupted.py", line 184, in _update_results
    "MAE": mean_absolute_error(train, train_imputed) if train.shape[0] > 0 and train_imputed.shape[0] > 0 else nan,
  File "/home/lhaag/.conda/envs/Data-Imputation-Thesis/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/lhaag/.conda/envs/Data-Imputation-Thesis/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 204, in mean_absolute_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/home/lhaag/.conda/envs/Data-Imputation-Thesis/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 101, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/home/lhaag/.conda/envs/Data-Imputation-Thesis/lib/python3.8/site-packages/sklearn/utils/validation.py", line 959, in check_array
    _assert_all_finite(
  File "/home/lhaag/.conda/envs/Data-Imputation-Thesis/lib/python3.8/site-packages/sklearn/utils/validation.py", line 124, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/home/lhaag/.conda/envs/Data-Imputation-Thesis/lib/python3.8/site-packages/sklearn/utils/validation.py", line 173, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.
